language: php

sudo: false

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: 7.0
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --prefer-dist

script:
  - php bin/parser --parser=native
  - php bin/parser --parser=riimu
  - php bin/parser --parser=pear
  - php bin/parser --parser=league
  - php bin/parser --parser=zend
  - php bin/benchmark --parser=native
  - php bin/benchmark --parser=riimu
  - php bin/benchmark --parser=pear
  - php bin/benchmark --parser=league
  - php bin/benchmark --parser=zend
